openapi: 3.0.1
info:
  title: accountDetails
  description: API Definition of accountDetails
  version: 1.0.0
servers:
- url: http://localhost:8290/accountdetails
paths:
  /:
    get:
      responses:
        default:
          description: Default response
