openapi: 3.0.1
info:
  title: account
  description: API Definition of account
  version: 1.0.0
servers:
- url: http://localhost:8290/account
paths:
  /:
    get:
      responses:
        default:
          description: Default response
