openapi: 3.0.1
info:
  title: paymentInfo
  description: API Definition of paymentInfo
  version: 1.0.0
servers:
- url: http://localhost:8290/paymentinfo
paths:
  /:
    get:
      responses:
        default:
          description: Default response
