openapi: 3.0.1
info:
  title: transactionHistory
  description: API Definition of transactionHistory
  version: 1.0.0
servers:
- url: http://localhost:8290/transactionhistory
paths:
  /:
    get:
      responses:
        default:
          description: Default response
