openapi: 3.0.1
info:
  title: transactionDetails
  description: API Definition of transactionDetails
  version: 1.0.0
servers:
- url: http://localhost:8290/transactiondetails
paths:
  /:
    get:
      responses:
        default:
          description: Default response
